CREATE TABLE blog(
blog_id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(75) NOT NULL,
cata VARCHAR(40) NOT NULL,
sub_cata VARCHAR(40) ,
keywords VARCHAR(2000) NOT NULL,
content_d VARCHAR(2200) NOT NULL,
image VARCHAR(300) NOT NULL,
icon VARCHAR(300) NOT NULL,
HTML MEDIUMTEXT NOT NULL,
views INT,
date_created DATE
);
